AutoForm.hooks({
  insertTutorialForm:{
    after:{
     insert:function(doc){
        $('#addTutorialForm').addClass('hidden');
        $('#addTutorial').removeClass('hidden');
       }
     }
  }
});