AutoForm.hooks({
  insertRootCommentForm:{
    after:{
     insert:function(doc){
        $('#addCommentForm').addClass('hidden');
        $('#addComment').removeClass('hidden');
       }
     }
  }
});